# https://taskfile.dev

version: '3'

tasks:

  train-500:
    cmds:
      - go run . -samples 500 -batchsize 32 -iterations 200 -lr 0.001 

  train-1000:
    cmds:
      - go run . -samples 1000 -batchsize 32 -lr 0.005 -hidden-layers 64 
    

  train-2000:
    cmds:
      - go run . -samples 2000 -batchsize 32 -lr 0.005 -hidden-layers 128 -iterations 600

  train-5000:
    cmds:
      - go run . -samples 5000 -batchsize 64 -lr 0.003 -hidden-layers 128 -iterations 600

  train-all:
    cmds:
      - go run . -batchsize 384 -lr 0.0025 -hidden-layers 192 -iterations 700
