# https://taskfile.dev

version: '3'

tasks:

  train-10:
    cmds:
      - go run . -samples 10 -batchsize 64 -lr 0.0015 -iterations 150

  train-500:
    cmds:
      - go run . -samples 500 -batchsize 64 -iterations 200 -lr 0.001 

  train-1000:
    cmds:
      - go run . -samples 1000 -batchsize 64 -iterations 200 -lr 0.002
    

  train-2000:
    cmds:
      - go run . -samples 2000 -batchsize 64 -lr 0.0015 -iterations 60

  train-5000:
    cmds:
      - go run . -samples 5000 -batchsize 128 -lr 0.001 -iterations 100

  train-all:
    cmds:
      - go run . -batchsize=256 -iterations=30 -lr=0.0008

  load-and-predict:
    cmds:
      # - go run . -load=fully-trained-model/image_classifier_final.json -predict=./images-to-predict/w.png
      - go run . -load=saved_models/image_classifier_final.json -predict=./images-to-predict/w.png
